Algoritmo "medidas"

Var

    a,b,c, areaQuadrado, areaTriangulo, areaTrapezio : real

Inicio

    escreva("Digite a medida A: ")
    leia(a)
    escreva("Digite a medida B: ")
    leia(b)
    escreva("Digite a medida C: ")
    leia(c)

    areaQuadrado <- a * a
    areaTriangulo <- (a * b) / 2
    areaTrapezio <- (a + b)  * C / 2

    escreval("Area do QUADRADO = ", areaQuadrado)
    escreval("Area do TRIANGULO = ", areaTriangulo)
    escreval("Area do TRAPEZIO = ", areaTrapezio)
    