Algoritmo "quadrantes"

Var
x,y: real


Inicio
escreva("Digite os valores das coordenadas x e y:")
leia(x)
leia(y)

enquanto(x<>0) e (y<>0)faca

se (x > 0)e (y >0) entao
escreva("Q1")
senao
se (x < 0 )e (y > 0) entao
escreva("Q2")
senao
se (x < 0)e (y < 0) entao
escreva("Q3")
senao
se (x > 0)e (y > 0) entao
escreva("Q4")
fimse
fimse
fimse

escreva("Digite os valores das coordenadas x e y:")
leia (x)
leia(y)

fimenquanto


Fimalgoritmo